apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cdsire8el-python 
  janus-idp.io/tekton: cdsire8el-python
  backstage.io/kubernetes-id: cdsire8el-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cdsire8el-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml